name: SSH Server Installation and Configuration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH server
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-server

      - name: Configure SSH server
        run: |
          # パスワードなしのSSHアクセスを有効化
          sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Set up SSH key
        run: |
          # SSH鍵の生成
          ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
          # 公開鍵の表示
          cat ~/.ssh/id_rsa.pub

      - name: Display SSH public key
        run: |
          echo "SSH Public Key:"
          cat ~/.ssh/id_rsa.pub
          
      - name: install playit
        run: |
          curl -SsL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/playit.gpg >/dev/null
          echo "deb [signed-by=/etc/apt/trusted.gpg.d/playit.gpg] https://playit-cloud.github.io/ppa/data ./" | sudo tee /etc/apt/sources.list.d/playit-cloud.list
          sudo apt update
          sudo apt install playit
          sleep 15s
          playit

      - name: Sleep for 6 hour
        run: sleep 6h

      # - name: run playit
      #   run: |
      #     wget https://github.com/playit-cloud/playit-agent/releases/download/v0.15.0/playit-linux-amd64
      #     chmod +x playit-linux-amd64
      #     ./playit-linux-amd64
